name: Test Rust Code

on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Cargo Run Check
        run: cargo check
      - name: Cargo Run Test
        run: cargo test 
      - name: Cargo Run Fmt
        run: cargo fmt -- --check
      - name: Cargo Run Clippy
        run: cargo clippy --all-targets -- -D warnings